stages:
  preprocessing:
    cmd: python -m kaicc.preprocess
      --input_triples_file_path ${triples.path.all}
      --input_images_archive ${images.path.archive}
      --output_triples_file_path ${triples.path.filtered}
      --output_labels_file_path ${labels.path.all}
      --output_images_directory ${images.path.directory}
    deps:
    - kaicc/preprocess.py
    - ${triples.path.all}
    - ${images.path.archive}
    outs:
    - ${triples.path.filtered}
    - ${labels.path.all}

  node_texts_generation:
    cmd: python -m kaicc.generate_node_texts
      --input_triples_file_path ${triples.path.filtered}
      --output_node_texts_file_path ${texts.path.entities}
    deps:
    - kaicc/generate_node_texts.py
    - ${triples.path.filtered}
    outs:
    - ${texts.path.entities}

  labels_splitting:
    cmd: python -m kaicc.split_labels
      --input_labels_file_path ${labels.path.all}
      --output_pretraining_labels_file_path ${labels.path.pretraining.all}
      --output_clustering_labels_file_path ${labels.path.clustering.all}
      --pretraining_labels_ratio ${labels.ratio.pretraining_to_all}
      --random_seed ${random.seed}
    deps:
    - kaicc/split_labels.py
    - ${labels.path.all}
    outs:
    - ${labels.path.pretraining.all}
    - ${labels.path.clustering.all}
