stages:
  preprocessing:
    cmd: python -m kaicc.preprocess
      --input_triples_file_path ${triples.path.all}
      --output_triples_file_path ${triples.path.filtered}
      --output_labels_file_path ${labels.path.clustering.all}
    deps:
    - kaicc/preprocess.py
    - ${triples.path.all}
    outs:
    - ${triples.path.filtered}
    - ${labels.path.clustering.all}

  node_texts_generation:
    cmd: python -m kaicc.generate_node_texts
      --input_triples_file_path ${triples.path.filtered}
      --output_node_texts_file_path ${texts.path.entities}
    deps:
    - kaicc/generate_node_texts.py
    - ${triples.path.filtered}
    outs:
    - ${texts.path.entities}

  image_vs_image_raw_clustering:
    cmd: python -m kaicc.cluster_image_vs_image_raw
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --output_run_id_path ${run_id.file_path.image_vs_image_raw}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
    deps:
    - kaicc/cluster_image_vs_image_raw.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    outs:
    - ${run_id.file_path.image_vs_image_raw}

  image_vs_image_clustering:
    cmd: python -m kaicc.cluster_image_vs_image
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --output_run_id_path ${run_id.file_path.image_vs_image}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
    deps:
    - kaicc/cluster_image_vs_image.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    outs:
    - ${run_id.file_path.image_vs_image}

  image_vs_text_clustering:
    cmd: python -m kaicc.cluster_image_vs_text
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.image_vs_text}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
    deps:
    - kaicc/cluster_image_vs_text.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.image_vs_text}

  image_vs_text_raw_clustering:
    cmd: python -m kaicc.cluster_image_vs_text_raw
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.image_vs_text_raw}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
    deps:
    - kaicc/cluster_image_vs_text_raw.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.image_vs_text_raw}

  transformed_image_vs_text_clustering:
    cmd: python -m kaicc.cluster_transformed_image_vs_text
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.transformed_image_vs_text}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
    deps:
    - kaicc/cluster_transformed_image_vs_text.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.transformed_image_vs_text}

  transformed_image_vs_text_raw_clustering:
    cmd: python -m kaicc.cluster_transformed_image_vs_text_raw
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.transformed_image_vs_text_raw}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
    deps:
    - kaicc/cluster_transformed_image_vs_text_raw.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.transformed_image_vs_text_raw}

  transformed_image_vs_transformed_image_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.image_vs_image}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.image_vs_image}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  transformed_image_vs_transformed_image_raw_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.image_vs_image_raw}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.image_vs_image_raw}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  image_vs_text_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.image_vs_text}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.image_vs_text}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  image_vs_text_raw_double_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.image_vs_text_raw}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.image_vs_text_raw}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  transformed_image_vs_text_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.transformed_image_vs_text}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.transformed_image_vs_text}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  transformed_image_vs_text_raw_double_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.transformed_image_vs_text_raw}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.transformed_image_vs_text_raw}
    - ${images.path.archive}
    - ${labels.path.clustering.all}
