stages:
  preprocessing:
    cmd: python -m kaicc.preprocess
      --input_triples_file_path ${triples.path.all}
      --output_triples_file_path ${triples.path.filtered}
      --output_labels_file_path ${labels.path.clustering.all}
    deps:
    - kaicc/preprocess.py
    - ${triples.path.all}
    outs:
    - ${triples.path.filtered}
    - ${labels.path.clustering.all}

  entities_enumeration:
    cmd: python -m kaicc.enumerate_entities
      --input_triples_file_path ${triples.path.filtered}
      --output_triples_file_path ${triples.path.enumerated}
    deps:
    - kaicc/enumerate_entities.py
    - ${triples.path.filtered}
    outs:
    - ${triples.path.enumerated}

  node_texts_generation:
    cmd: python -m kaicc.generate_node_texts
      --input_triples_file_path ${triples.path.enumerated}
      --output_node_texts_file_path ${texts.path.entities}
    deps:
    - kaicc/generate_node_texts.py
    - ${triples.path.enumerated}
    outs:
    - ${texts.path.entities}

  transformed_image_vs_transformed_image_raw_single_projection_clustering:
    cmd: python -m kaicc.cluster_trans_img_vs_trans_img_raw_1_proj
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --output_run_id_path ${run_id.file_path.transformed_image_vs_transformed_image_raw_single_projection}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
      --freeze_temperature_embeddings ${freeze_temperature_embeddings}
      --freeze_temperature_clusters ${freeze_temperature_clusters}
    deps:
    - kaicc/cluster_trans_img_vs_trans_img_raw_1_proj.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    outs:
    - ${run_id.file_path.transformed_image_vs_transformed_image_raw_single_projection}

  transformed_image_vs_transformed_image_single_projection_clustering:
    cmd: python -m kaicc.cluster_trans_img_vs_trans_img_1_proj
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --output_run_id_path ${run_id.file_path.transformed_image_vs_transformed_image_single_projection}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
      --freeze_temperature_embeddings ${freeze_temperature_embeddings}
      --freeze_temperature_clusters ${freeze_temperature_clusters}
    deps:
    - kaicc/cluster_trans_img_vs_trans_img_1_proj.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    outs:
    - ${run_id.file_path.transformed_image_vs_transformed_image_single_projection}

  image_vs_text_single_projection_clustering:
    cmd: python -m kaicc.cluster_img_vs_txt_1_proj
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.image_vs_text_single_projection}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --freeze_temperature_embeddings ${freeze_temperature_embeddings}
      --freeze_temperature_clusters ${freeze_temperature_clusters}
      --random_text_slicing ${random_text_slicing}
    deps:
    - kaicc/cluster_img_vs_txt_1_proj.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.image_vs_text_single_projection}

  image_vs_text_raw_double_projection_clustering:
    cmd: python -m kaicc.cluster_img_vs_txt_raw_2_proj
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.image_vs_text_raw_double_projection}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --freeze_temperature_embeddings ${freeze_temperature_embeddings}
      --freeze_temperature_clusters ${freeze_temperature_clusters}
      --random_text_slicing ${random_text_slicing}
    deps:
    - kaicc/cluster_img_vs_txt_raw_2_proj.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.image_vs_text_raw_double_projection}

  transformed_image_vs_text_single_projection_clustering:
    cmd: python -m kaicc.cluster_trans_img_vs_txt_1_proj
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.transformed_image_vs_text_single_projection}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
      --freeze_temperature_embeddings ${freeze_temperature_embeddings}
      --freeze_temperature_clusters ${freeze_temperature_clusters}
      --random_text_slicing ${random_text_slicing}
    deps:
    - kaicc/cluster_trans_img_vs_txt_1_proj.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.transformed_image_vs_text_single_projection}

  transformed_image_vs_text_raw_double_projection_clustering:
    cmd: python -m kaicc.cluster_trans_img_vs_txt_raw_2_proj
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --captions_file_path ${images.captions.path}
      --output_run_id_path ${run_id.file_path.transformed_image_vs_text_raw_double_projection}
      --clip_base_model_name ${training.clip_base_model_name}
      --random_seed ${random.seed}
      --patience ${training.patience}
      --clusters_count ${training.clusters_count}
      --embeddings_dimension ${training.embeddings_dimension}
      --epochs_count ${training.epochs_count}
      --learning_rate ${training.learning_rate}
      --batch_size ${training.batch_size}
      --regularization_strength ${training.regularization_strength}
      --temperature_embeddings ${training.temperature_embeddings}
      --temperature_clusters ${training.temperature_clusters}
      --size ${transform.size}
      --scale ${transform.scale}
      --brightness ${transform.brightness}
      --contrast ${transform.contrast}
      --saturation ${transform.saturation}
      --hue ${transform.hue}
      --p_color_jitter ${transform.p_color_jitter}
      --p_gray_scale ${transform.p_gray_scale}
      --p_gaussian_blur ${transform.p_gaussian_blur}
      --sigma ${transform.sigma}
      --freeze_temperature_embeddings ${freeze_temperature_embeddings}
      --freeze_temperature_clusters ${freeze_temperature_clusters}
      --random_text_slicing ${random_text_slicing}
    deps:
    - kaicc/cluster_trans_img_vs_txt_raw_2_proj.py
    - ${images.path.archive}
    - ${labels.path.clustering.all}
    - ${images.captions.path}
    outs:
    - ${run_id.file_path.transformed_image_vs_text_raw_double_projection}

  transformed_image_vs_transformed_image_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --n_samples ${n_samples}
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.transformed_image_vs_transformed_image_single_projection}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.transformed_image_vs_transformed_image_single_projection}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  transformed_image_vs_transformed_image_raw_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --n_samples ${n_samples}
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.transformed_image_vs_transformed_image_raw_single_projection}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.transformed_image_vs_transformed_image_raw_single_projection}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  image_vs_text_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --n_samples ${n_samples}
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.image_vs_text_single_projection}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.image_vs_text_single_projection}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  image_vs_text_raw_double_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --n_samples ${n_samples}
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.image_vs_text_raw_double_projection}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.image_vs_text_raw_double_projection}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  transformed_image_vs_text_single_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --n_samples ${n_samples}
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.transformed_image_vs_text_single_projection}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.transformed_image_vs_text_single_projection}
    - ${images.path.archive}
    - ${labels.path.clustering.all}

  transformed_image_vs_text_raw_double_projection_evaluation:
    cmd: python -m kaicc.evaluate
      --n_samples ${n_samples}
      --random_seed ${random.seed}
      --run_id_path ${run_id.file_path.transformed_image_vs_text_raw_double_projection}
      --size ${transform.size}
      --image_archive_path ${images.path.archive}
      --image_directory_path ${images.path.directory}
      --labels_file_path ${labels.path.clustering.all}
      --batch_size ${training.batch_size}
    deps:
    - kaicc/evaluate.py
    - ${run_id.file_path.transformed_image_vs_text_raw_double_projection}
    - ${images.path.archive}
    - ${labels.path.clustering.all}
